version: '3'

services:
    jekyll:
        image: jekyll/jekyll:4.2.2
        command: jekyll serve --trace --incremental --watch --force_polling --verbose
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll